In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])
b = np.array([[1,2],[3,4],[5,6]])
c = np.zeros((0,2))
d = np.empty((5,6),dtype=int)


In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [17]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
c

array([], shape=(0, 2), dtype=float64)

In [19]:
d

array([[      3026068188712,                 205,                   0,
                          0,   25896032864829440, 4189022153932546683],
       [3543545871972049440, 4195437666033020210, 3833458496703705140,
        2318265678939828275, 2478221553439042850, 3545288623737937978],
       [3990863503164453175, 3918744542737740845, 3690197646408771123,
        2477321082607330357, 8385534776637005868, 7287422581096149113],
       [8241417393971357048, 3180232325849248101, 8028074750225097248,
        7018122393524249198, 7147543803067511910, 3271356283909661492],
       [3618697470305919544, 4063202563773706808, 7310315409581548131,
        2322206376885055090, 8243124581912289826, 2459029316100385139]])

In [24]:
e= np.eye(4,4) #e= np.eye(N=4)
f= np.eye(4,4,k=1,dtype=int)


In [25]:
e


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
f

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

# Dimensionality reduction

In [42]:
g = np.arange(0,20,1)

In [43]:
h= np.reshape(g,(4,5))

In [38]:
np.linspace(0,50,num=11,dtype=int)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [44]:
h[:,4]

array([ 4,  9, 14, 19])

In [46]:
array1= np.arange(10,25)

In [47]:
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
array1[[0,4,5]]

array([10, 14, 15])

In [52]:
array2=np.array([1,2,3,4,5])

In [53]:
array2[[True,True,False,False,False]]

array([1, 2])

In [55]:
array2[array2>3]

array([4, 5])